#!/usr/bin/env python3
"""Generates supabase/seed.sql.

Demo data for the beta: two workspaces, three brands, seven watches whose
parts cover every component (some shared within a brand, some unique), a
ticket at every stage per brand plus closed ones, and demo sign-ins for
every role. Deterministic ids (a0000000-0000-4000-8000-0000000NNNNN) so
the file can be re-run; demo tickets are reset on each run, user-created
tickets are untouched.

    python3 supabase/seed.py > supabase/seed.sql
"""
from __future__ import annotations

import json

def uid(n: int) -> str:
    return f"a0000000-0000-4000-8000-{n:012d}"

def q(v) -> str:
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, (dict, list)):
        return "'" + json.dumps(v).replace("'", "''") + "'::jsonb"
    return "'" + str(v).replace("'", "''") + "'"

out: list[str] = []
def emit(s: str = "") -> None:
    out.append(s)

# ------------------------------------------------------------------ tenancy
NODUS_WS, CX_WS = uid(1), uid(2)
NODUS, SANGIN, AWAKE = uid(11), uid(21), uid(22)
DEMO_PASSWORD = "PivotDemo2026!!"

emit("-- GENERATED by supabase/seed.py — edit that file, not this one.")
emit("-- Demo data for the beta. Every insert is idempotent; demo tickets are reset on each run.")
emit()
emit("insert into workspaces (id, name, slug, ticket_prefix, send_from_email, send_from_name, send_return_label_enabled, bench_address) values")
emit(f"  ({q(NODUS_WS)}, 'Nodus', 'nodus', 'NW', 'customerservice@noduswatches.com', 'Nodus Service Team', false, {q({'name': 'Rane · Pivot Service Center', 'line1': '2110 Harbor Ave SW', 'city': 'Seattle', 'state': 'WA', 'postal_code': '98126', 'country': 'United States'})}),")
emit(f"  ({q(CX_WS)}, 'Connexus', 'connexus', 'CX', 'service@connexus.example', 'Connexus Service', false, null)")
emit("on conflict (id) do update set name = excluded.name, ticket_prefix = excluded.ticket_prefix, send_from_email = excluded.send_from_email, send_from_name = excluded.send_from_name, bench_address = coalesce(workspaces.bench_address, excluded.bench_address);")
emit()
emit("insert into brands (id, workspace_id, name, slug) values")
emit(f"  ({q(NODUS)}, {q(NODUS_WS)}, 'Nodus', 'nodus'),")
emit(f"  ({q(SANGIN)}, {q(CX_WS)}, 'Sangin', 'sangin'),")
emit(f"  ({q(AWAKE)}, {q(CX_WS)}, 'Awake', 'awake')")
emit("on conflict (id) do nothing;")
emit()

# ------------------------------------------------------------------ catalog
# watches: (id, workspace, model, reference, warranty, brand)
WATCHES = [
    (101, NODUS_WS, "Sector Deep", "NW-SD-01", 24, NODUS),
    (102, NODUS_WS, "Avalon II", "NW-AV2-01", 24, NODUS),
    (103, NODUS_WS, "Sector GMT", "NW-SGMT-01", 24, NODUS),
    (104, NODUS_WS, "Contrail GMT", "NW-CT-01", 24, NODUS),
    (111, CX_WS, "Kinetic II", "SG-K2", 24, SANGIN),
    (112, CX_WS, "Neptune", "SG-NEP", 24, SANGIN),
    (121, CX_WS, "Mission One", "AW-M1", 12, AWAKE),
]
SD, AV2, SGMT, CT, K2, NEP, M1 = 101, 102, 103, 104, 111, 112, 121

# parts: (id, workspace, sku, name, component, cost, reorder_at, opening_qty, fits[])
PARTS = [
    # --- Nodus: shared across the Sector family / everything
    (204, NODUS_WS, "MV-NH35", "NH35 movement", "movement", 45, 3, 4, [SD, AV2]),
    (207, NODUS_WS, "MV-NH34", "NH34 GMT movement", "movement", 58, 2, 3, [SGMT, CT]),
    (205, NODUS_WS, "GK-UNI-01", "Gasket set", "gaskets", 3, 15, 40, [SD, AV2, SGMT, CT]),
    (202, NODUS_WS, "CR-SD-01", "Crown, signed", "crown_tube", 12, 4, 11, [SD, SGMT]),
    (201, NODUS_WS, "CT-SD-01", "Casetube", "crown_tube", 8, 5, 2, [SD, SGMT]),
    (208, NODUS_WS, "CRY-SEC-40", "Sapphire crystal, Sector 40mm", "crystal", 38, 2, 6, [SD, SGMT]),
    (209, NODUS_WS, "BR-SEC-01", "Sector bracelet", "bracelet", 65, 2, 3, [SD, SGMT]),
    (210, NODUS_WS, "CL-NW-01", "Nodus clasp, signed", "clasp", 22, 4, 9, [SD, AV2, SGMT, CT]),
    (211, NODUS_WS, "LM-C3-01", "Lume kit, C3", "lume", 15, 2, 5, [SD, AV2, SGMT, CT]),
    (212, NODUS_WS, "HD-SEC-01", "Sector hands set", "hands", 18, 2, 4, [SD, SGMT]),
    (216, NODUS_WS, "CB-SEC-01", "Caseback, Sector", "caseback", 20, 2, 5, [SD, SGMT]),
    # --- Nodus: unique to a model
    (203, NODUS_WS, "BZ-SD-CER", "Bezel insert, ceramic", "bezel_insert", 52, 2, 3, [SD]),
    (214, NODUS_WS, "CS-SD-01", "Case, Sector Deep", "case", 110, 1, 2, [SD]),
    (217, NODUS_WS, "DL-SD-01", "Dial, Sector Deep", "dial", 48, 2, 0, [SD]),
    (213, NODUS_WS, "BZ-SGMT-24", "Bezel insert, GMT 24h", "bezel_insert", 55, 2, 2, [SGMT]),
    (215, NODUS_WS, "CS-SGMT-01", "Case, Sector GMT", "case", 110, 1, 1, [SGMT]),
    (218, NODUS_WS, "DL-SGMT-01", "Dial, Sector GMT", "dial", 48, 2, 0, [SGMT]),
    (206, NODUS_WS, "DL-AV2-01", "Dial, Avalon II", "dial", 60, 2, 0, [AV2]),
    (219, NODUS_WS, "CS-AV2-01", "Case, Avalon II", "case", 95, 1, 2, [AV2]),
    (220, NODUS_WS, "CB-AV2-01", "Caseback, Avalon II", "caseback", 18, 2, 4, [AV2]),
    (221, NODUS_WS, "BZ-AV2-ST", "Bezel insert, Avalon II steel", "bezel_insert", 40, 2, 3, [AV2]),
    (222, NODUS_WS, "BR-AV2-01", "Avalon bracelet", "bracelet", 60, 2, 2, [AV2]),
    (223, NODUS_WS, "CR-AV2-01", "Crown, Avalon", "crown_tube", 12, 4, 6, [AV2]),
    (224, NODUS_WS, "CRY-AV2-38", "Sapphire crystal, Avalon 38mm", "crystal", 36, 2, 4, [AV2]),
    (225, NODUS_WS, "HD-AV2-01", "Hands, Avalon", "hands", 16, 2, 3, [AV2]),
    (226, NODUS_WS, "DL-CT-01", "Dial, Contrail GMT", "dial", 50, 2, 2, [CT]),
    (227, NODUS_WS, "CS-CT-01", "Case, Contrail", "case", 105, 1, 1, [CT]),
    (228, NODUS_WS, "CB-CT-01", "Caseback, Contrail", "caseback", 20, 2, 3, [CT]),
    (229, NODUS_WS, "BZ-CT-01", "Bezel insert, Contrail", "bezel_insert", 45, 2, 1, [CT]),
    (230, NODUS_WS, "BR-CT-01", "Contrail bracelet", "bracelet", 62, 2, 2, [CT]),
    (231, NODUS_WS, "CR-CT-01", "Crown, Contrail", "crown_tube", 12, 4, 7, [CT]),
    (232, NODUS_WS, "CRY-CT-41", "Sapphire crystal, Contrail 41mm", "crystal", 38, 2, 3, [CT]),
    (233, NODUS_WS, "HD-CT-01", "Hands, Contrail GMT", "hands", 20, 2, 2, [CT]),
    # --- Connexus / Sangin: shared across both Sangin models
    (301, CX_WS, "SG-MV-NH35", "NH35 movement (Sangin)", "movement", 45, 3, 5, [K2, NEP]),
    (302, CX_WS, "SG-GK-01", "Gasket set (Sangin)", "gaskets", 3, 10, 25, [K2, NEP]),
    (303, CX_WS, "SG-CL-01", "Sangin clasp", "clasp", 20, 3, 6, [K2, NEP]),
    (304, CX_WS, "SG-CR-01", "Sangin crown", "crown_tube", 11, 4, 8, [K2, NEP]),
    (305, CX_WS, "SG-LM-01", "Lume kit (Sangin)", "lume", 15, 2, 3, [K2, NEP]),
    (306, CX_WS, "SG-BR-01", "Sangin rubber strap", "bracelet", 30, 3, 7, [K2, NEP]),
    # --- Sangin: unique
    (307, CX_WS, "SG-K2-BZ", "Bezel insert, Kinetic II", "bezel_insert", 42, 2, 2, [K2]),
    (308, CX_WS, "SG-K2-CS", "Case, Kinetic II", "case", 100, 1, 1, [K2]),
    (309, CX_WS, "SG-K2-CB", "Caseback, Kinetic II", "caseback", 18, 2, 3, [K2]),
    (310, CX_WS, "SG-K2-CRY", "Sapphire crystal, Kinetic II", "crystal", 35, 2, 0, [K2]),
    (311, CX_WS, "SG-K2-DL", "Dial, Kinetic II", "dial", 46, 2, 2, [K2]),
    (312, CX_WS, "SG-K2-HD", "Hands, Kinetic II", "hands", 17, 2, 4, [K2]),
    (313, CX_WS, "SG-NEP-BZ", "Bezel insert, Neptune", "bezel_insert", 44, 2, 3, [NEP]),
    (314, CX_WS, "SG-NEP-CS", "Case, Neptune", "case", 100, 1, 2, [NEP]),
    (315, CX_WS, "SG-NEP-CB", "Caseback, Neptune", "caseback", 18, 2, 2, [NEP]),
    (316, CX_WS, "SG-NEP-CRY", "Sapphire crystal, Neptune", "crystal", 35, 2, 5, [NEP]),
    (317, CX_WS, "SG-NEP-DL", "Dial, Neptune", "dial", 46, 2, 1, [NEP]),
    (318, CX_WS, "SG-NEP-HD", "Hands, Neptune", "hands", 17, 2, 3, [NEP]),
    # --- Awake / Mission One: its own set
    (320, CX_WS, "AW-M1-MV", "Miyota 9015 movement", "movement", 70, 2, 2, [M1]),
    (321, CX_WS, "AW-M1-GK", "Gasket set (Awake)", "gaskets", 3, 10, 18, [M1]),
    (322, CX_WS, "AW-M1-CL", "Awake clasp", "clasp", 24, 3, 4, [M1]),
    (323, CX_WS, "AW-M1-CR", "Crown, Mission One", "crown_tube", 13, 4, 0, [M1]),
    (324, CX_WS, "AW-M1-LM", "Lume kit (Awake)", "lume", 15, 2, 2, [M1]),
    (325, CX_WS, "AW-M1-BR", "Mission One bracelet", "bracelet", 68, 2, 2, [M1]),
    (326, CX_WS, "AW-M1-BZ", "Bezel insert, Mission One", "bezel_insert", 48, 2, 2, [M1]),
    (327, CX_WS, "AW-M1-CS", "Case, Mission One", "case", 115, 1, 1, [M1]),
    (328, CX_WS, "AW-M1-CB", "Caseback, Mission One", "caseback", 22, 2, 3, [M1]),
    (329, CX_WS, "AW-M1-CRY", "Sapphire crystal, Mission One", "crystal", 40, 2, 3, [M1]),
    (330, CX_WS, "AW-M1-DL", "Dial, Mission One", "dial", 55, 2, 2, [M1]),
    (331, CX_WS, "AW-M1-HD", "Hands, Mission One", "hands", 19, 2, 3, [M1]),
]
COMPONENTS = ["bezel_insert", "bracelet", "case", "caseback", "clasp", "crown_tube", "crystal", "dial", "gaskets", "hands", "lume", "movement"]
for wid, *_ in WATCHES:
    covered = {p[4] for p in PARTS if wid in p[8]}
    missing = set(COMPONENTS) - covered
    assert not missing, f"watch {wid} missing {missing}"

emit("-- ---------------------------------------------------------------- catalog (demo)")
emit("insert into watches (id, workspace_id, model, reference, warranty_months) values")
emit(",\n".join(f"  ({q(uid(i))}, {q(ws)}, {q(m)}, {q(r)}, {w})" for i, ws, m, r, w, _ in WATCHES))
emit("on conflict (id) do update set model = excluded.model, reference = excluded.reference, warranty_months = excluded.warranty_months, is_active = true;")
emit()
emit("insert into watch_brands (watch_id, brand_id, is_primary) values")
emit(",\n".join(f"  ({q(uid(i))}, {q(b)}, true)" for i, _, _, _, _, b in WATCHES))
emit("on conflict do nothing;")
emit()
emit("insert into parts (id, workspace_id, sku, name, component, unit_cost, reorder_at) values")
emit(",\n".join(f"  ({q(uid(i))}, {q(ws)}, {q(sku)}, {q(name)}, {q(comp)}, {cost}, {ro})" for i, ws, sku, name, comp, cost, ro, _, _ in PARTS))
emit("on conflict (id) do update set sku = excluded.sku, name = excluded.name, component = excluded.component, unit_cost = excluded.unit_cost, reorder_at = excluded.reorder_at, is_active = true;")
emit()
emit("-- Fits are pure demo configuration: reset them for the demo watches.")
emit(f"delete from watch_parts where watch_id in ({', '.join(q(uid(i)) for i, *_ in WATCHES)});")
emit("insert into watch_parts (watch_id, part_id) values")
emit(",\n".join(f"  ({q(uid(w))}, {q(uid(i))})" for i, *_, fits in PARTS for w in fits))
emit("on conflict do nothing;")
emit()
emit("-- The stock ledger is reset to the opening counts on every run (all parts are demo parts).")
emit("-- Rows on tickets created through the app are unlinked first so they don't block the reset.")
emit("update ticket_parts set stock_movement_id = null, used_at = null where stock_movement_id is not null;")
emit("delete from part_orders;")
emit("delete from stock_movements;")
emit("-- Legacy demo tickets from the first seed.")
emit("delete from tickets where id in (" + ", ".join(q(uid(i)) for i in range(401, 407)) + ");")
emit("insert into stock_movements (id, part_id, qty_delta, reason, unit_cost_at_time, note) values")
rows = [f"  ({q(uid(5000 + i))}, {q(uid(i))}, {qty}, 'initial_count', {cost}, 'demo seed')" for i, _, _, _, _, cost, _, qty, _ in PARTS if qty > 0]
emit(",\n".join(rows))
emit("on conflict (id) do nothing;")
emit()
emit("-- Reorders in progress for two of the out-of-stock parts.")
emit("insert into part_orders (id, part_id, qty, ordered_at, expected_at, note) values")
emit(f"  ({q(uid(6001))}, {q(uid(206))}, 5, current_date - 3, current_date + 10, 'demo seed · PO 1182'),")
emit(f"  ({q(uid(6002))}, {q(uid(310))}, 4, current_date - 6, current_date + 4, 'demo seed'),")
emit(f"  ({q(uid(6003))}, {q(uid(218))}, 3, current_date - 2, current_date + 8, 'demo seed · PO 1190');")
emit()

# ------------------------------------------------------------------ people
USERS = [
    (901, "owner.demo@pivot.test", "Wes (demo)", [("owner", None, None)]),
    (902, "cullen.demo@pivot.test", "Cullen (demo)", [("owner", None, None)]),
    (903, "rane.demo@pivot.test", "Rane (demo)", [("watchmaker", None, NODUS), ("watchmaker", None, SANGIN), ("watchmaker", None, AWAKE)]),
    (904, "nodus.rep.demo@pivot.test", "Nodus rep (demo)", [("brand_rep", None, NODUS)]),
    (905, "sangin.rep.demo@pivot.test", "Sangin rep (demo)", [("brand_rep", None, SANGIN)]),
    (906, "connexus.admin.demo@pivot.test", "Connexus admin (demo)", [("admin", CX_WS, None)]),
]
WES, CULLEN, RANE, NODUS_REP, SANGIN_REP, CX_ADMIN = (uid(n) for n in (901, 902, 903, 904, 905, 906))
emit("-- ---------------------------------------------------------------- demo people")
emit(f"-- Every demo sign-in uses the password {DEMO_PASSWORD!r}. Re-running the seed resets it.")
emit("insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token, email_change, email_change_token_new) values")
emit(",\n".join(
    f"  ({q(uid(i))}, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', {q(email)}, extensions.crypt({q(DEMO_PASSWORD)}, extensions.gen_salt('bf')), now(), '{{\"provider\":\"email\",\"providers\":[\"email\"]}}'::jsonb, {q({'display_name': name})}, now(), now(), '', '', '', '')"
    for i, email, name, _ in USERS))
emit("on conflict (id) do update set encrypted_password = excluded.encrypted_password, email_confirmed_at = coalesce(auth.users.email_confirmed_at, now());")
emit()
emit("insert into auth.identities (id, user_id, provider_id, provider, identity_data, last_sign_in_at, created_at, updated_at) values")
emit(",\n".join(
    f"  ({q(uid(950 + k))}, {q(uid(i))}, {q(uid(i))}, 'email', {q({'sub': uid(i), 'email': email, 'email_verified': True})}, now(), now(), now())"
    for k, (i, email, _, _) in enumerate(USERS)))
emit("on conflict (provider_id, provider) do nothing;")
emit()
emit("insert into profiles (id, email, display_name) values")
emit(",\n".join(f"  ({q(uid(i))}, {q(email)}, {q(name)})" for i, email, name, _ in USERS))
emit("on conflict (id) do update set display_name = excluded.display_name, is_active = true;")
emit()
emit("insert into memberships (user_id, role, workspace_id, brand_id) values")
emit(",\n".join(f"  ({q(uid(i))}, {q(role)}, {q(ws)}, {q(b)})" for i, _, _, grants in USERS for role, ws, b in grants))
emit("on conflict (user_id, role, workspace_id, brand_id) do nothing;")
emit()

# ------------------------------------------------------------------ tickets
STAGES = ["intake", "received", "request_part", "in_repair", "testing", "shipped_back", "closed"]
PATH = ["intake", "received", "request_part", "in_repair", "testing", "shipped_back", "closed"]

# per brand: (prefix, workspace, brand, watches, customers, rep, base ticket number)
BRANDS = [
    ("NW", NODUS_WS, NODUS, [SD, AV2, SGMT, CT], NODUS_REP, 2600, [
        ("Dana Whitmore", "dana.w@example.com", "Bezel doesn’t click anymore and rotates freely."),
        ("Maria Lopez", "maria@example.com", "Second hand stutters and the watch loses about two minutes a day."),
        ("James Whitfield", "james@example.com", "Crown fell off while setting the time."),
        ("Adam Ferguson", "adam@example.com", "Bezel insert cracked after a drop."),
        ("Sarah Chen", "sarah@example.com", "Fogging under the crystal after swimming."),
        ("Leo Park", "leo@example.com", "Running slow, needs regulation."),
        ("Tom Reyes", "tom@example.com", "Clasp would not stay closed."),
        ("Priya Nair", "priya@example.com", "Lume barely glows on the hour markers."),
    ]),
    ("CX", CX_WS, SANGIN, [K2, NEP], SANGIN_REP, 2600, [
        ("Kai Tanaka", "kai.t@example.com", "Crystal chipped at 4 o’clock."),
        ("Elena Ruiz", "elena@example.com", "Bezel action feels gritty."),
        ("Marcus Hill", "marcus@example.com", "Stem is loose; crown won’t screw down."),
        ("Yuki Sato", "yuki@example.com", "Movement stopped after a knock."),
        ("Owen Brooks", "owen@example.com", "Water ingress; dial spotting."),
        ("Nina Kowalski", "nina@example.com", "Runs fast by a minute a day."),
        ("Ravi Patel", "ravi@example.com", "Clasp spring bar sheared."),
        ("Hana Ito", "hana@example.com", "Lume faded on hands."),
    ]),
    ("CX", CX_WS, AWAKE, [M1], SANGIN_REP, 2650, [
        ("Zach Kim", "zach@example.com", "Crown came off in the pocket."),
        ("Lucía Fernández", "lucia@example.com", "Dial has a loose index."),
        ("Ben Osei", "ben@example.com", "Bezel insert scratched deeply."),
        ("Chloé Martin", "chloe@example.com", "Movement hairspring stuck."),
        ("Ivan Petrov", "ivan@example.com", "Caseback gasket perished."),
        ("Grace Lee", "grace@example.com", "Bracelet pin missing."),
        ("Noah Adams", "noah@example.com", "Crystal fogging."),
        ("Mia Rossi", "mia@example.com", "Hands misaligned after service elsewhere."),
    ]),
]

# For each stage, which component gets replaced (drives parts + stock) and a second repair-only row.
PLAN = {
    "intake":       {"replace": [], "repair": []},
    "received":     {"replace": ["bezel_insert"], "repair": []},
    "request_part": {"replace": ["dial", "crystal", "crown_tube"], "repair": ["movement"]},
    "in_repair":    {"replace": ["bezel_insert"], "repair": ["case"]},
    "testing":      {"replace": ["gaskets"], "repair": ["crystal"]},
    "shipped_back": {"replace": [], "repair": ["movement"]},
    "closed":       {"replace": ["clasp"], "repair": []},
    "closed2":      {"replace": ["lume"], "repair": ["hands"]},
}
CONDITIONS = {"bezel_insert": ["Cracked"], "dial": ["Scratches"], "crown_tube": ["Cracked"], "movement": [], "case": ["Scratches"], "gaskets": [], "crystal": ["Discolored"], "clasp": ["Lightly worn"], "lume": ["Discolored"], "hands": ["Lightly worn"]}

def part_for(watch: int, component: str) -> tuple[int, str, str] | None:
    """The first catalog part of this component that fits the watch."""
    for i, _, sku, name, comp, *_r in PARTS:
        fits = _r[-1]
        if comp == component and watch in fits:
            return i, name, sku
    return None

ticket_rows, part_rows, event_rows, move_rows, ship_rows = [], [], [], [], []
tid = 4000
pid = 4100
eid = 4300
mid = 5400
sid = 4600
ticket_ids = []

def days(n: float) -> str:
    return f"now() - interval '{n} days'"

for prefix, ws, brand, watches, rep, base, customers in BRANDS:
    seq = 0
    stage_list = STAGES + ["closed2"]
    for k, key in enumerate(stage_list):
        stage = "closed" if key == "closed2" else key
        tid += 1
        seq += 1
        ticket_ids.append(tid)
        name, email, issue = customers[k]
        watch = watches[k % len(watches)]
        number = f"{prefix}26{base % 100 + seq:04d}" if prefix == "CX" and brand == AWAKE else f"{prefix}26{(base % 100) + seq:04d}"
        # numbering: NW260001.., CX260001.. (Sangin), CX260051.. (Awake)
        n = (base - 2600) + seq if prefix == "CX" else seq
        number = f"{prefix}26{n:04d}"
        plan = PLAN[key]
        reached = PATH.index(stage)
        created_days = 30 - 3 * k
        received_days = created_days - 1 if reached >= 1 else None
        intake = [{"component": c, "conditions": CONDITIONS.get(c, ["Lightly worn"]) or ["Lightly worn"]} for c in plan["replace"] + plan["repair"]] if reached >= 1 else []
        done = reached >= 4  # testing and later: the plan was carried out
        cats = [{"component": c, "action": "replace", "planned": True, **({"done": True} if done else {}), "has_part": True} for c in plan["replace"]] + [{"component": c, "action": "repair" if c != "movement" else "regulate", "planned": True, **({"done": True} if done else {})} for c in plan["repair"]]
        cats = cats if reached >= 1 else []
        repair_complete = reached >= 4
        checks = {"timekeeping": reached >= 5, "water_resistance": reached >= 5, "visual": reached >= 5} if reached >= 4 else {"timekeeping": reached >= 4, "water_resistance": False, "visual": False}
        closed_at = days(created_days - 12) if stage == "closed" else None
        priority = key == "in_repair"
        requires_payment = key in ("testing", "closed2")
        coverage = "paid" if requires_payment else ("warranty" if reached >= 3 else None)
        addr = {"line1": f"{100 + tid % 900} Market St", "city": "Los Angeles" if prefix == "NW" else "Portland", "state": "CA" if prefix == "NW" else "OR", "postal_code": "90013" if prefix == "NW" else "97204", "country": "United States"}
        ticket_rows.append(
            f"  ({q(uid(tid))}, {q(number)}, {q(ws)}, {q(brand)}, {q(stage)}, {q(name)}, {q(email)}, {q(uid(watch))}, {q(f'{500000 + tid}')}, {q(issue)}, "
            f"{q(priority)}, {q(requires_payment)}, {q(coverage)}, {q('paid' if key == 'closed2' else ('invoiced' if requires_payment else 'none'))}, "
            f"{days(received_days) if received_days is not None else 'null'}, {q(intake)}, {q(cats)}, {q(repair_complete)}, {q(checks)}, {closed_at or 'null'}, "
            f"{days(created_days)}, {days(max(created_days - 3 * reached, 0.5))}, {days(created_days - 2) if reached >= 2 and plan['replace'] else 'null'}, {q(addr)}, "
            f"{'true' if key == 'shipped_back' else 'false'})"
        )
        # events: created + each stage reached, actor by stage owner
        eid += 1
        event_rows.append(f"  ({q(uid(eid))}, {q(uid(tid))}, 'created', {q(rep)}, null, 'intake', {days(created_days)})")
        for s_i in range(1, reached + 1):
            frm, to = PATH[s_i - 1], PATH[s_i]
            actor = RANE if to in ("received", "in_repair", "testing", "shipped_back", "closed") else rep
            if to == "request_part":
                actor = RANE
            eid += 1
            event_rows.append(f"  ({q(uid(eid))}, {q(uid(tid))}, 'stage_changed', {q(actor)}, {q(frm)}, {q(to)}, {days(created_days - 1.5 * s_i)})")
        # parts: replace rows; sent once past request_part; consumed once in in_repair or later
        for comp in (plan["replace"] if reached >= 1 else []):
            p = part_for(watch, comp)
            if not p:
                continue
            p_id, p_name, p_sku = p
            pid += 1
            sent = reached >= 3
            consumed = reached >= 3
            move_ref = "null"
            if consumed:
                mid += 1
                cost = next(pp[5] for pp in PARTS if pp[0] == p_id)
                move_rows.append(f"  ({q(uid(mid))}, {q(uid(p_id))}, -1, 'used_on_ticket', {q(uid(tid))}, {cost}, {q(RANE)}, {days(created_days - 5)})")
                move_ref = q(uid(mid))
            part_rows.append(
                f"  ({q(uid(pid))}, {q(uid(tid))}, {q(uid(p_id))}, {q(comp)}, {q(p_name)}, {q(p_sku)}, 'brand', {days(created_days - 2)}, {q(RANE)}, "
                f"{days(created_days - 3) if sent else 'null'}, {q(rep) if sent else 'null'}, {move_ref}, {days(created_days - 5) if consumed else 'null'})"
            )
        if stage == "closed":
            sid += 1
            ship_rows.append(f"  ({q(uid(sid))}, {q(uid(tid))}, 'outbound', 'manual', 'usps', {q(f'9400 1108 {tid}')}, {days(created_days - 12)}, {days(created_days - 9)})")

emit("-- ---------------------------------------------------------------- demo tickets")
emit("-- One ticket per stage for each brand, plus two closed. Reset on every run (ledger rows for them too);")
emit("-- tickets created through the app keep their own ids and are never touched.")
emit(f"delete from stock_movements where ticket_id in ({', '.join(q(uid(t)) for t in ticket_ids)});")
emit(f"delete from tickets where id in ({', '.join(q(uid(t)) for t in ticket_ids)});")
emit("alter table tickets disable trigger tickets_updated_at;")
emit("insert into tickets (id, ticket_number, workspace_id, brand_id, stage, customer_name, customer_email, watch_id, watch_serial, issue_description, priority, requires_payment, coverage, payment_status, watch_received_at, intake_components, repair_categories, repair_complete, testing_checks, closed_at, created_at, updated_at, parts_requested_at, return_address, in_person_handoff) values")
emit(",\n".join(ticket_rows) + ";")
emit("alter table tickets enable trigger tickets_updated_at;")
emit()
emit("insert into ticket_events (id, ticket_id, type, actor_id, from_stage, to_stage, created_at) values")
emit(",\n".join(event_rows) + ";")
emit()
if move_rows:
    emit("insert into stock_movements (id, part_id, qty_delta, reason, ticket_id, unit_cost_at_time, created_by, created_at) values")
    emit(",\n".join(move_rows) + ";")
    emit()
emit("insert into ticket_parts (id, ticket_id, part_id, component, name, sku, source, requested_at, requested_by, sent_at, sent_by, stock_movement_id, used_at) values")
emit(",\n".join(part_rows) + ";")
emit()
emit("insert into shipments (id, ticket_id, direction, source, carrier_code, tracking_number, shipped_at, delivered_at) values")
emit(",\n".join(ship_rows) + ";")
emit()
print("\n".join(out))
